// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameParticipant = "participant"

// Participant mapped from table <participant>
type Participant struct {
	ID               int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name             string         `gorm:"column:name;not null" json:"name"`
	Address          string         `gorm:"column:address;not null" json:"address"`
	LuckyNum         int64          `gorm:"column:lucky_num;not null" json:"lucky_num"`
	ProjectID        int64          `gorm:"column:project_id;not null" json:"project_id"`
	ProjectOnchainID int64          `gorm:"column:project_onchain_id;not null" json:"project_onchain_id"`
	Win              bool           `gorm:"column:win;not null" json:"win"`
	MerkleProof      string         `gorm:"column:merkle_proof;not null;comment:数组字符串" json:"merkle_proof"` // 数组字符串
	CreatedAt        time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Participant's table name
func (*Participant) TableName() string {
	return TableNameParticipant
}
